# -*- coding: utf-8 -*-
"""Coding practice

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWEOjcufols94cXbJhXopqdFqpgguzbZ
"""

n = int(input())
if n%2!=0:
    print("Weird")
elif (n%2==0 and 2<= n <=5):
    print("Not Weird")
elif(n%2==0 and 6<= n <=20):
    print("Weird")
elif(n%2==0 and n>20):
    print("Not Weird")