# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FWEOjcufols94cXbJhXopqdFqpgguzbZ
"""

w=int(input("enter a number:"))
if(w>2 and w%2==0):
    print("YES")
else:
    print("NO")
